// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Categories documents */
interface CategoriesDocumentData {
    /**
     * Name field in *Categories*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: categories.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.RichTextField;
    /**
     * type field in *Categories*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: categories.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    type: prismicT.RichTextField;
}
/**
 * Categories document from Prismic
 *
 * - **API ID**: `categories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoriesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<CategoriesDocumentData>, "categories", Lang>;
/** Content for Home documents */
interface HomeDocumentData {
    /**
     * CTA Actions field in *Home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.cta_actions[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    cta_actions: prismicT.GroupField<Simplify<HomeDocumentDataCtaActionsItem>>;
    /**
     * Title field in *Home*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Home*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * illustrations field in *Home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.illustrations[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    illustrations: prismicT.GroupField<Simplify<HomeDocumentDataIllustrationsItem>>;
}
/**
 * Item in Home → CTA Actions
 *
 */
export interface HomeDocumentDataCtaActionsItem {
    /**
     * title field in *Home → CTA Actions*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.cta_actions[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * route field in *Home → CTA Actions*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.cta_actions[].route
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    route: prismicT.KeyTextField;
}
/**
 * Item in Home → illustrations
 *
 */
export interface HomeDocumentDataIllustrationsItem {
    /**
     * image field in *Home → illustrations*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.illustrations[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for Labels documents */
interface LabelsDocumentData {
    /**
     * Hide Todo field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.hide_todo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    hide_todo: prismicT.RichTextField;
    /**
     * Edit Todo Action field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.edit_todo_action
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    edit_todo_action: prismicT.RichTextField;
    /**
     * Delete Todo Action field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.delete_todo_action
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    delete_todo_action: prismicT.RichTextField;
    /**
     * Edit Todo field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.edit_todo
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    edit_todo: prismicT.RichTextField;
    /**
     * Add Todo field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.add_todo
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    add_todo: prismicT.RichTextField;
    /**
     * Title field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.title
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.description
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Tags field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.tags
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tags: prismicT.RichTextField;
    /**
     * Cancel field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.cancel
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    cancel: prismicT.RichTextField;
    /**
     * Add field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.add
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    add: prismicT.RichTextField;
    /**
     * Save field in *Labels*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: labels.save
     * - **Tab**: Form
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    save: prismicT.RichTextField;
}
/**
 * Labels document from Prismic
 *
 * - **API ID**: `labels`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LabelsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<LabelsDocumentData>, "labels", Lang>;
/** Content for Todos documents */
interface TodosDocumentData {
    /**
     * title field in *Todos*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: todos.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Todos*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: todos.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<TodosDocumentDataSlicesSlice>;
}
/**
 * Slice for *Todos → Slice Zone*
 *
 */
type TodosDocumentDataSlicesSlice = TodoCategorySlice;
/**
 * Todos document from Prismic
 *
 * - **API ID**: `todos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TodosDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<TodosDocumentData>, "todos", Lang>;
export type AllDocumentTypes = CategoriesDocument | HomeDocument | LabelsDocument | TodosDocument;
/**
 * Primary content in TodoCategory → Primary
 *
 */
interface TodoCategorySliceDefaultPrimary {
    /**
     * Title field in *TodoCategory → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: todo_category.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * legend field in *TodoCategory → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: todo_category.primary.legend
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    legend: prismicT.ColorField;
}
/**
 * Default variation for TodoCategory Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TodoCategory`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TodoCategorySliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TodoCategorySliceDefaultPrimary>, never>;
/**
 * Slice variation for *TodoCategory*
 *
 */
type TodoCategorySliceVariation = TodoCategorySliceDefault;
/**
 * TodoCategory Shared Slice
 *
 * - **API ID**: `todo_category`
 * - **Description**: `TodoCategory`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TodoCategorySlice = prismicT.SharedSlice<"todo_category", TodoCategorySliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { CategoriesDocumentData, CategoriesDocument, HomeDocumentData, HomeDocumentDataCtaActionsItem, HomeDocumentDataIllustrationsItem, HomeDocument, LabelsDocumentData, LabelsDocument, TodosDocumentData, TodosDocumentDataSlicesSlice, TodosDocument, AllDocumentTypes, TodoCategorySliceDefaultPrimary, TodoCategorySliceDefault, TodoCategorySliceVariation, TodoCategorySlice };
    }
}
